@ContosoPizza_HostAddress = http://localhost:5052

GET {{ContosoPizza_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "isGlutenFree": false
}

###

PUT {{ContosoPizza_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

GET {{ContosoPizza_HostAddress}}/pizza/3
Accept: application/json

###

DELETE {{ContosoPizza_HostAddress}}/pizza/3

###

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Pepperoni",
    "isGlutenFree": false
}

###

POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

PUT {{ContosoPizza_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Pepperoni",
    "isGlutenFree": false
}

###

PUT {{ContosoPizza_HostAddress}}/pizza/4
Content-Type: application/json

{
    "id": 4,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/pizza/3
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/pizza/4
Accept: application/json

###

DELETE {{ContosoPizza_HostAddress}}/pizza/4

###

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###